use std::fmt::Write;

use forge_ir::{ForgeFunction, Inst, IrType, Terminator, Value};

use crate::avx2::Avx2Selector;
use crate::schedule::ListScheduler;

/// Code-emitter errors.
#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    /// IR type has no Rust representation in this backend.
    #[error("unsupported Rust type emission for `{0}`")]
    UnsupportedType(String),
}

/// Emits one function as Rust+AVX2 source.
pub fn emit_function(func: &ForgeFunction, symbol_name: &str) -> Result<String, EmitError> {
    let mut out = String::new();
    writeln!(&mut out, "// AUTO-GENERATED by Forge compiler -- do not edit").ok();
    writeln!(&mut out, "#![allow(warnings)]").ok();
    writeln!(&mut out, "#[allow(unused_imports)]").ok();
    writeln!(&mut out, "use std::arch::x86_64::*;").ok();
    writeln!(&mut out).ok();
    writeln!(&mut out, "#[target_feature(enable = \"avx2,fma\")]").ok();
    writeln!(&mut out, "#[no_mangle]").ok();
    write!(&mut out, "pub unsafe extern \"C\" fn {}(", symbol_name).ok();
    let params = func
        .block(func.entry)
        .params
        .iter()
        .enumerate()
        .map(|(idx, v)| {
            let ty = rust_ty(func.value_type(*v).expect("entry param type"))?;
            Ok(format!("p{idx}: {ty}"))
        })
        .collect::<Result<Vec<_>, EmitError>>()?;
    write!(&mut out, "{}", params.join(", ")).ok();
    // Append thread/block/grid context parameters so every intrinsic can read real values.
    if !params.is_empty() {
        write!(&mut out, ", ").ok();
    }
    write!(&mut out,
        "_ctx_thread_x: u32, _ctx_thread_y: u32, _ctx_thread_z: u32, \
         _ctx_block_x: u32, _ctx_block_y: u32, _ctx_block_z: u32, \
         _ctx_block_dim_x: u32, _ctx_block_dim_y: u32, _ctx_block_dim_z: u32, \
         _ctx_grid_dim_x: u32, _ctx_grid_dim_y: u32, _ctx_grid_dim_z: u32"
    ).ok();
    writeln!(&mut out, ") {{").ok();
    writeln!(
        &mut out,
        "    // SAFETY: this function is generated with explicit architecture-gated intrinsics."
    )
    .ok();

    for value in &func.values {
        let ty = rust_ty(&value.ty)?;
        writeln!(
            &mut out,
            "    let mut v{}: {} = std::mem::zeroed();",
            value.id.0, ty
        )
        .ok();
    }
    for (idx, param) in func.block(func.entry).params.iter().enumerate() {
        writeln!(&mut out, "    v{} = p{};", param.0, idx).ok();
    }

    writeln!(&mut out, "    let mut bb: u32 = {};", func.entry.0).ok();
    writeln!(&mut out, "    loop {{").ok();
    writeln!(&mut out, "        match bb {{").ok();

    for block in func.block_ids() {
        writeln!(&mut out, "            {} => {{", block.0).ok();
        let schedule = ListScheduler::schedule_block(func, block);
        for inst_id in schedule {
            let inst = func.inst(inst_id);
            emit_inst_line(&mut out, func, inst)?;
        }
        match &func.block(block).terminator {
            Terminator::Return(_) => {
                writeln!(&mut out, "                break;").ok();
            }
            Terminator::Jump { target, args } => {
                for (idx, param) in func.block(*target).params.iter().enumerate() {
                    if let Some(arg) = args.get(idx) {
                        writeln!(&mut out, "                v{} = v{};", param.0, arg.0).ok();
                    }
                }
                writeln!(&mut out, "                bb = {};", target.0).ok();
                writeln!(&mut out, "                continue;").ok();
            }
            Terminator::Branch {
                cond,
                then_block,
                then_args,
                else_block,
                else_args,
            } => {
                writeln!(&mut out, "                if v{} {{", cond.0).ok();
                for (idx, param) in func.block(*then_block).params.iter().enumerate() {
                    if let Some(arg) = then_args.get(idx) {
                        writeln!(&mut out, "                    v{} = v{};", param.0, arg.0).ok();
                    }
                }
                writeln!(&mut out, "                    bb = {};", then_block.0).ok();
                writeln!(&mut out, "                }} else {{").ok();
                for (idx, param) in func.block(*else_block).params.iter().enumerate() {
                    if let Some(arg) = else_args.get(idx) {
                        writeln!(&mut out, "                    v{} = v{};", param.0, arg.0).ok();
                    }
                }
                writeln!(&mut out, "                    bb = {};", else_block.0).ok();
                writeln!(&mut out, "                }}").ok();
                writeln!(&mut out, "                continue;").ok();
            }
            Terminator::Unreachable => {
                writeln!(&mut out, "                break;").ok();
            }
        }
        writeln!(&mut out, "            }}").ok();
    }

    writeln!(&mut out, "            _ => break,").ok();
    writeln!(&mut out, "        }}").ok();
    writeln!(&mut out, "    }}").ok();
    writeln!(&mut out, "}}").ok();
    writeln!(&mut out).ok();

    let launcher_types = func
        .block(func.entry)
        .params
        .iter()
        .map(|v| rust_ty(func.value_type(*v).expect("entry param type")))
        .collect::<Result<Vec<_>, EmitError>>()?;
    emit_launcher(&mut out, symbol_name, &launcher_types);
    Ok(out)
}

fn emit_inst_line(out: &mut String, func: &ForgeFunction, inst: &Inst) -> Result<(), EmitError> {
    if let Some(result) = inst.result() {
        if let Some(expr) = Avx2Selector::emit_inst(inst, func.value_type(result)) {
            writeln!(out, "                v{} = {};", result.0, expr).ok();
            return Ok(());
        }
    }
    match inst {
        Inst::Const { result, value } => {
            writeln!(out, "                v{} = {};", result.0, emit_const_scalar(value)).ok();
        }
        Inst::IAdd { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} + v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::ISub { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} - v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::IMul { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} * v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::IDiv { result, lhs, rhs, .. } => {
            writeln!(out, "                v{} = v{} / v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::IRem { result, lhs, rhs, .. } => {
            writeln!(out, "                v{} = v{} % v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FAdd { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} + v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FSub { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} - v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FMul { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} * v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FDiv { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} / v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FMA { result, a, b, c } => {
            writeln!(
                out,
                "                v{} = v{} * v{} + v{};",
                result.0, a.0, b.0, c.0
            )
            .ok();
        }
        Inst::INeg { result, operand } | Inst::FNeg { result, operand } => {
            writeln!(out, "                v{} = -v{};", result.0, operand.0).ok();
        }
        Inst::And { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} & v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::Or { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} | v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::Xor { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} ^ v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::Not { result, operand } => {
            writeln!(out, "                v{} = !v{};", result.0, operand.0).ok();
        }
        Inst::Shl { result, lhs, rhs } => {
            writeln!(out, "                v{} = v{} << v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::Shr { result, lhs, rhs, .. } => {
            writeln!(out, "                v{} = v{} >> v{};", result.0, lhs.0, rhs.0).ok();
        }
        Inst::ICmp {
            result,
            pred,
            lhs,
            rhs,
        } => {
            let op = match pred {
                forge_ir::IntPred::Eq => "==",
                forge_ir::IntPred::Ne => "!=",
                forge_ir::IntPred::Slt | forge_ir::IntPred::Ult => "<",
                forge_ir::IntPred::Sle | forge_ir::IntPred::Ule => "<=",
                forge_ir::IntPred::Sgt | forge_ir::IntPred::Ugt => ">",
                forge_ir::IntPred::Sge | forge_ir::IntPred::Uge => ">=",
            };
            writeln!(out, "                v{} = v{} {} v{};", result.0, lhs.0, op, rhs.0).ok();
        }
        Inst::FCmp {
            result,
            pred,
            lhs,
            rhs,
        } => {
            let op = match pred {
                forge_ir::FloatPred::Oeq => "==",
                forge_ir::FloatPred::One => "!=",
                forge_ir::FloatPred::Olt => "<",
                forge_ir::FloatPred::Ole => "<=",
                forge_ir::FloatPred::Ogt => ">",
                forge_ir::FloatPred::Oge => ">=",
                forge_ir::FloatPred::Uno => "!=",
            };
            writeln!(out, "                v{} = v{} {} v{};", result.0, lhs.0, op, rhs.0).ok();
        }
        Inst::Load { result, ptr, ty, .. } => {
            let ty_str = rust_ty(ty)?;
            writeln!(
                out,
                "                v{} = *(v{} as *const {});",
                result.0, ptr.0, ty_str
            )
            .ok();
        }
        Inst::Store { ptr, value, .. } => {
            let ty = func
                .value_type(*value)
                .ok_or_else(|| EmitError::UnsupportedType("unknown store value type".to_owned()))?;
            let ty_str = rust_ty(ty)?;
            writeln!(
                out,
                "                *(v{} as *mut {}) = v{};",
                ptr.0, ty_str, value.0
            )
            .ok();
        }
        Inst::GetElementPtr {
            result,
            base,
            indices,
        } => {
            let idx = indices.first().copied().unwrap_or(Value(u32::MAX));
            writeln!(
                out,
                "                v{} = (v{} as *mut u8).add((v{} as usize) * 4) as _;",
                result.0, base.0, idx.0
            )
            .ok();
        }
        Inst::Alloca { result, ty, .. } => {
            let ty_str = rust_ty(ty)?;
            writeln!(
                out,
                "                let mut tmp_{}: {} = std::mem::zeroed();",
                result.0, ty_str
            )
            .ok();
            writeln!(out, "                v{} = &mut tmp_{} as *mut _ as _;", result.0, result.0).ok();
        }
        Inst::AtomicAdd { result, value, .. } => {
            writeln!(out, "                v{} = v{};", result.0, value.0).ok();
        }
        Inst::AtomicCAS { result, cmp, .. } => {
            writeln!(out, "                v{} = v{};", result.0, cmp.0).ok();
        }
        Inst::Prefetch { .. } => {}
        Inst::ZExt { result, operand, ty }
        | Inst::SExt { result, operand, ty }
        | Inst::Trunc { result, operand, ty }
        | Inst::FPToI { result, operand, ty, .. }
        | Inst::IToFP { result, operand, ty, .. }
        | Inst::FPExt { result, operand, ty }
        | Inst::FPTrunc { result, operand, ty }
        | Inst::Bitcast { result, operand, ty } => {
            let ty_str = rust_ty(ty)?;
            writeln!(
                out,
                "                v{} = v{} as {};",
                result.0, operand.0, ty_str
            )
            .ok();
        }
        Inst::Splat { result, scalar, .. } => {
            writeln!(out, "                v{} = _mm256_set1_ps(v{} as f32);", result.0, scalar.0).ok();
        }
        Inst::Extract { result, vec, idx } => {
            writeln!(
                out,
                "                v{} = _mm256_extract_epi32(_mm256_castps_si256(v{}), {}) as i32;",
                result.0, vec.0, idx
            )
            .ok();
        }
        Inst::Insert {
            result,
            vec,
            scalar,
            idx,
        } => {
            writeln!(
                out,
                "                v{} = _mm256_castsi256_ps(_mm256_insert_epi32(_mm256_castps_si256(v{}), v{} as i32, {}));",
                result.0, vec.0, scalar.0, idx
            )
            .ok();
        }
        Inst::Shuffle { result, a, .. } => {
            writeln!(out, "                v{} = v{};", result.0, a.0).ok();
        }
        Inst::Blend {
            result, a, b, mask, ..
        } => {
            writeln!(
                out,
                "                v{} = _mm256_blendv_ps(v{}, v{}, v{});",
                result.0, a.0, b.0, mask.0
            )
            .ok();
        }
        Inst::ThreadIdxX { result } => {
            writeln!(out, "                v{} = _ctx_thread_x;", result.0).ok();
        }
        Inst::ThreadIdxY { result } => {
            writeln!(out, "                v{} = _ctx_thread_y;", result.0).ok();
        }
        Inst::ThreadIdxZ { result } => {
            writeln!(out, "                v{} = _ctx_thread_z;", result.0).ok();
        }
        Inst::BlockIdxX { result } => {
            writeln!(out, "                v{} = _ctx_block_x;", result.0).ok();
        }
        Inst::BlockIdxY { result } => {
            writeln!(out, "                v{} = _ctx_block_y;", result.0).ok();
        }
        Inst::BlockIdxZ { result } => {
            writeln!(out, "                v{} = _ctx_block_z;", result.0).ok();
        }
        Inst::BlockDimX { result } => {
            writeln!(out, "                v{} = _ctx_block_dim_x;", result.0).ok();
        }
        Inst::BlockDimY { result } => {
            writeln!(out, "                v{} = _ctx_block_dim_y;", result.0).ok();
        }
        Inst::BlockDimZ { result } => {
            writeln!(out, "                v{} = _ctx_block_dim_z;", result.0).ok();
        }
        Inst::GridDimX { result } => {
            writeln!(out, "                v{} = _ctx_grid_dim_x;", result.0).ok();
        }
        Inst::GridDimY { result } => {
            writeln!(out, "                v{} = _ctx_grid_dim_y;", result.0).ok();
        }
        Inst::GridDimZ { result } => {
            writeln!(out, "                v{} = _ctx_grid_dim_z;", result.0).ok();
        }
        Inst::WarpLaneId { result } => {
            // Warp lane = thread_x % WARP_LANES (8 for AVX2).
            writeln!(out, "                v{} = _ctx_thread_x % 8u32;", result.0).ok();
        }
        Inst::FSqrt { result, operand } => {
            writeln!(out, "                v{} = _mm256_sqrt_ps(v{});", result.0, operand.0).ok();
        }
        Inst::FMin { result, lhs, rhs } => {
            writeln!(out, "                v{} = _mm256_min_ps(v{}, v{});", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FMax { result, lhs, rhs } => {
            writeln!(out, "                v{} = _mm256_max_ps(v{}, v{});", result.0, lhs.0, rhs.0).ok();
        }
        Inst::FAbs { result, operand } => {
            // AVX2 abs: mask off sign bit.
            writeln!(out,
                "                v{} = _mm256_and_ps(v{}, _mm256_castsi256_ps(_mm256_set1_epi32(0x7FFF_FFFF_u32 as i32)));",
                result.0, operand.0).ok();
        }
        Inst::Gather { result, base, indices, scale, .. } => {
            writeln!(out,
                "                v{} = _mm256_i32gather_ps(v{} as *const f32, v{}, {});",
                result.0, base.0, indices.0, scale).ok();
        }
        Inst::Scatter { base, indices, value, scale, .. } => {
            // AVX2 has no native scatter; emit scalar loop fallback.
            writeln!(out, "                {{ // scatter fallback").ok();
            writeln!(out, "                    let base_ptr = v{} as *mut f32;" , base.0).ok();
            writeln!(out, "                    let idx_arr: [i32; 8] = std::mem::transmute(v{});" , indices.0).ok();
            writeln!(out, "                    let val_arr: [f32; 8] = std::mem::transmute(v{});" , value.0).ok();
            writeln!(out, "                    for lane in 0usize..8 {{").ok();
            writeln!(out, "                        *base_ptr.add(idx_arr[lane] as usize * {} as usize) = val_arr[lane];" , scale).ok();
            writeln!(out, "                    }}").ok();
            writeln!(out, "                }}").ok();
        }
        Inst::SyncBlock | Inst::SyncWarp | Inst::MemFence { .. } => {}
        Inst::Undef { result, ty } => {
            let ty_str = rust_ty(ty)?;
            writeln!(
                out,
                "                v{} = std::mem::zeroed::<{}>();",
                result.0, ty_str
            )
            .ok();
        }
        Inst::Call { result, func, args } => {
            if let Some(result) = result {
                writeln!(
                    out,
                    "                v{} = {}({});",
                    result.0,
                    func.name,
                    args.iter()
                        .map(|a| format!("v{}", a.0))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .ok();
            } else {
                writeln!(
                    out,
                    "                {}({});",
                    func.name,
                    args.iter()
                        .map(|a| format!("v{}", a.0))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .ok();
            }
        }
    }
    Ok(())
}

fn emit_const_scalar(value: &forge_ir::ConstValue) -> String {
    match value {
        forge_ir::ConstValue::F32(v) => format!("{v}f32"),
        forge_ir::ConstValue::F64(v) => format!("{v}f64"),
        forge_ir::ConstValue::I32(v) => format!("{v}i32"),
        forge_ir::ConstValue::I64(v) => format!("{v}i64"),
        forge_ir::ConstValue::U32(v) => format!("{v}u32"),
        forge_ir::ConstValue::U64(v) => format!("{v}u64"),
        forge_ir::ConstValue::Bool(v) => format!("{v}"),
    }
}

fn rust_ty(ty: &IrType) -> Result<String, EmitError> {
    Ok(match ty {
        IrType::F32 => "f32".to_owned(),
        IrType::F64 => "f64".to_owned(),
        IrType::I32 => "i32".to_owned(),
        IrType::I64 => "i64".to_owned(),
        IrType::U32 => "u32".to_owned(),
        IrType::U64 => "u64".to_owned(),
        IrType::Bool => "bool".to_owned(),
        IrType::Ptr { elem, mutable: _ } => format!("*mut {}", rust_ty(elem)?),
        IrType::Vector { elem, lanes } if **elem == IrType::F32 && *lanes == 8 => "__m256".to_owned(),
        IrType::Vector { elem, lanes } if **elem == IrType::I32 && *lanes == 8 => "__m256i".to_owned(),
        IrType::Void => "()".to_owned(),
        other => return Err(EmitError::UnsupportedType(other.to_string())),
    })
}

/// Emits the launcher wrapper that dispatches to the AVX2 kernel
/// (or a scalar stub if AVX2 is not detected at runtime).
fn emit_launcher(out: &mut String, symbol_name: &str, param_types: &[String]) {
    // --- AVX2 context parameter block ---
    // Thread/block/grid indices are appended to every kernel signature so that
    // the generated code can read them rather than emitting stub zeros.
    writeln!(out, "/// Safe launcher for `{}` with AVX2 runtime detection.", symbol_name).ok();
    writeln!(out, "pub fn launch_{}(", symbol_name).ok();
    for (i, ty) in param_types.iter().enumerate() {
        writeln!(out, "    p{}: {},", i, ty).ok();
    }
    writeln!(out, "    grid_x: u32, grid_y: u32, grid_z: u32,").ok();
    writeln!(out, "    block_x: u32, block_y: u32, block_z: u32,").ok();
    writeln!(out, ") {{").ok();
    // Runtime AVX2 detection.
    writeln!(out, "    if is_x86_feature_detected!(\"avx2\") && is_x86_feature_detected!(\"fma\") {{").ok();
    writeln!(out, "        // SAFETY: AVX2 + FMA detected at runtime.").ok();
    writeln!(out, "        unsafe {{").ok();
    writeln!(out, "            launch_{}_avx2(", symbol_name).ok();
    for i in 0..param_types.len() {
        writeln!(out, "                p{},", i).ok();
    }
    writeln!(out, "                grid_x, grid_y, grid_z, block_x, block_y, block_z,").ok();
    writeln!(out, "            );").ok();
    writeln!(out, "        }}").ok();
    writeln!(out, "    }} else {{").ok();
    writeln!(out, "        // SAFETY: AVX2 not available; scalar path also uses #[target_feature].").ok();
    writeln!(out, "        unsafe {{").ok();
    writeln!(out, "            launch_{}_scalar(", symbol_name).ok();
    for i in 0..param_types.len() {
        writeln!(out, "                p{},", i).ok();
    }
    writeln!(out, "                grid_x, grid_y, grid_z, block_x, block_y, block_z,").ok();
    writeln!(out, "            );").ok();
    writeln!(out, "        }}").ok();
    writeln!(out, "    }}").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    // --- AVX2 path ---
    writeln!(out, "#[target_feature(enable = \"avx2,fma\")]").ok();
    writeln!(out, "unsafe fn launch_{}_avx2(", symbol_name).ok();
    emit_launcher_params(out, param_types);
    writeln!(out, ") {{").ok();
    emit_launcher_body(out, symbol_name, param_types);
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    // --- Scalar fallback path (no SIMD) ---
    // NOTE: Even the "scalar" path must be #[target_feature] + unsafe because
    // the kernel function uses __m256 in its signature (generated with AVX2).
    // The actual AVX2-vs-scalar distinction is in the calling code.
    writeln!(out, "#[target_feature(enable = \"avx2,fma\")]").ok();
    writeln!(out, "unsafe fn launch_{}_scalar(", symbol_name).ok();
    emit_launcher_params(out, param_types);
    writeln!(out, ") {{").ok();
    writeln!(out, "    // Scalar fallback: same loop topology.").ok();
    emit_launcher_body(out, symbol_name, param_types);
    writeln!(out, "}}").ok();
}

fn emit_launcher_params(out: &mut String, param_types: &[String]) {
    for (i, ty) in param_types.iter().enumerate() {
        writeln!(out, "    p{}: {},", i, ty).ok();
    }
    writeln!(out, "    grid_x: u32, grid_y: u32, grid_z: u32,").ok();
    writeln!(out, "    block_x: u32, block_y: u32, block_z: u32,").ok();
}

fn emit_launcher_body(out: &mut String, symbol_name: &str, param_types: &[String]) {
    writeln!(out, "    for bz in 0..grid_z {{").ok();
    writeln!(out, "        for by in 0..grid_y {{").ok();
    writeln!(out, "            for bx in 0..grid_x {{").ok();
    writeln!(out, "                for tz in 0..block_z {{").ok();
    writeln!(out, "                    for ty in 0..block_y {{").ok();
    writeln!(out, "                        for tx in 0..block_x {{").ok();
    writeln!(out, "                            // SAFETY: kernel uses #[target_feature]; always unsafe.").ok();
    writeln!(out, "                            unsafe {{").ok();
    write!(out,   "                                {}(", symbol_name).ok();
    for i in 0..param_types.len() {
        write!(out, "p{}, ", i).ok();
    }
    write!(out, "tx, ty, tz, bx, by, bz, block_x, block_y, block_z, grid_x, grid_y, grid_z").ok();
    writeln!(out, ");").ok();
    writeln!(out, "                            }}").ok(); // unsafe
    writeln!(out, "                        }}").ok(); // tx
    writeln!(out, "                    }}").ok(); // ty
    writeln!(out, "                }}").ok(); // tz
    writeln!(out, "            }}").ok(); // bx
    writeln!(out, "        }}").ok(); // by
    writeln!(out, "    }}").ok(); // bz
}

#[cfg(test)]
mod tests {
    use forge_ir::{ConstValue, ForgeFunction, Inst, IrType, Terminator};

    use super::*;

    #[test]
    fn emits_avx2_add_for_vector_add() {
        let mut f = ForgeFunction::new("add");
        let ty = IrType::Vector {
            elem: Box::new(IrType::F32),
            lanes: 8,
        };
        let a = f.add_block_param(f.entry, ty.clone());
        let b = f.add_block_param(f.entry, ty.clone());
        let out = f.fresh_value(ty);
        f.append_inst(f.entry, Inst::FAdd { result: out, lhs: a, rhs: b });
        f.set_terminator(f.entry, Terminator::Return(Some(out)));
        let code = emit_function(&f, "forge_kernel_add").expect("emit should succeed");
        assert!(code.contains("_mm256_add_ps"));
    }

    #[test]
    fn emits_fma_instruction_when_present() {
        let mut f = ForgeFunction::new("fma");
        let ty = IrType::Vector {
            elem: Box::new(IrType::F32),
            lanes: 8,
        };
        let a = f.add_block_param(f.entry, ty.clone());
        let b = f.add_block_param(f.entry, ty.clone());
        let c = f.add_block_param(f.entry, ty.clone());
        let out = f.fresh_value(ty);
        f.append_inst(f.entry, Inst::FMA { result: out, a, b, c });
        f.set_terminator(f.entry, Terminator::Return(Some(out)));
        let code = emit_function(&f, "forge_kernel_fma").expect("emit should succeed");
        assert!(code.contains("_mm256_fmadd_ps"));
    }

    #[test]
    fn emits_scalar_constants() {
        let mut f = ForgeFunction::new("const");
        let v = f.fresh_value(IrType::F32);
        f.append_inst(
            f.entry,
            Inst::Const {
                result: v,
                value: ConstValue::F32(1.0),
            },
        );
        f.set_terminator(f.entry, Terminator::Return(Some(v)));
        let code = emit_function(&f, "forge_kernel_const").expect("emit should succeed");
        assert!(code.contains("1f32"));
    }
}
