// AUTO-GENERATED by Forge compiler -- do not edit
#![allow(warnings)]
#[allow(unused_imports)]
use std::arch::x86_64::*;

#[target_feature(enable = "avx2,fma")]
#[no_mangle]
pub unsafe extern "C" fn forge_kernel_matmul(p0: *mut f32, p1: *mut f32, p2: *mut f32, p3: u32, _ctx_thread_x: u32, _ctx_thread_y: u32, _ctx_thread_z: u32, _ctx_block_x: u32, _ctx_block_y: u32, _ctx_block_z: u32, _ctx_block_dim_x: u32, _ctx_block_dim_y: u32, _ctx_block_dim_z: u32, _ctx_grid_dim_x: u32, _ctx_grid_dim_y: u32, _ctx_grid_dim_z: u32) {
    // SAFETY: this function is generated with explicit architecture-gated intrinsics.
    let mut v0: *mut f32 = std::mem::zeroed();
    let mut v1: *mut f32 = std::mem::zeroed();
    let mut v2: *mut f32 = std::mem::zeroed();
    let mut v3: u32 = std::mem::zeroed();
    let mut v4: u32 = std::mem::zeroed();
    let mut v5: u32 = std::mem::zeroed();
    let mut v6: bool = std::mem::zeroed();
    let mut v7: bool = std::mem::zeroed();
    let mut v8: bool = std::mem::zeroed();
    let mut v9: *mut f32 = std::mem::zeroed();
    let mut v10: *mut f32 = std::mem::zeroed();
    let mut v11: *mut f32 = std::mem::zeroed();
    let mut v12: u32 = std::mem::zeroed();
    let mut v13: u32 = std::mem::zeroed();
    let mut v14: u32 = std::mem::zeroed();
    let mut v15: f64 = std::mem::zeroed();
    let mut v16: u32 = std::mem::zeroed();
    let mut v17: u32 = std::mem::zeroed();
    let mut v18: u32 = std::mem::zeroed();
    let mut v19: u32 = std::mem::zeroed();
    let mut v20: *mut f32 = std::mem::zeroed();
    let mut v21: *mut f32 = std::mem::zeroed();
    let mut v22: *mut f32 = std::mem::zeroed();
    let mut v23: *mut f32 = std::mem::zeroed();
    let mut v24: *mut f32 = std::mem::zeroed();
    let mut v25: *mut f32 = std::mem::zeroed();
    let mut v26: u32 = std::mem::zeroed();
    let mut v27: u32 = std::mem::zeroed();
    let mut v28: u32 = std::mem::zeroed();
    let mut v29: u32 = std::mem::zeroed();
    let mut v30: u32 = std::mem::zeroed();
    let mut v31: u32 = std::mem::zeroed();
    let mut v32: f32 = std::mem::zeroed();
    let mut v33: f32 = std::mem::zeroed();
    let mut v34: bool = std::mem::zeroed();
    let mut v35: u32 = std::mem::zeroed();
    let mut v36: u32 = std::mem::zeroed();
    let mut v37: *mut f32 = std::mem::zeroed();
    let mut v38: f32 = std::mem::zeroed();
    let mut v39: u32 = std::mem::zeroed();
    let mut v40: u32 = std::mem::zeroed();
    let mut v41: *mut f32 = std::mem::zeroed();
    let mut v42: f32 = std::mem::zeroed();
    let mut v43: f32 = std::mem::zeroed();
    let mut v44: f32 = std::mem::zeroed();
    let mut v45: u32 = std::mem::zeroed();
    let mut v46: u32 = std::mem::zeroed();
    let mut v47: u32 = std::mem::zeroed();
    let mut v48: u32 = std::mem::zeroed();
    let mut v49: *mut f32 = std::mem::zeroed();
    v0 = p0;
    v1 = p1;
    v2 = p2;
    v3 = p3;
    let mut bb: u32 = 0;
    loop {
        match bb {
            0 => {
                if v8 {
                    bb = 1;
                } else {
                    bb = 2;
                }
                continue;
            }
            1 => {
                v18 = v16;
                v20 = v0;
                v22 = v1;
                v24 = v2;
                v26 = v3;
                v28 = v4;
                v30 = v5;
                v32 = v15;
                bb = 4;
                continue;
            }
            2 => {
                v9 = v0;
                v10 = v1;
                v11 = v2;
                v12 = v3;
                v13 = v4;
                v14 = v5;
                bb = 3;
                continue;
            }
            3 => {
                break;
            }
            4 => {
                if v34 {
                    bb = 5;
                } else {
                    v19 = v18;
                    v21 = v20;
                    v23 = v22;
                    v25 = v24;
                    v27 = v26;
                    v29 = v28;
                    v31 = v30;
                    v33 = v32;
                    bb = 6;
                }
                continue;
            }
            5 => {
                v18 = v46;
                v20 = v20;
                v22 = v22;
                v24 = v24;
                v26 = v26;
                v28 = v28;
                v30 = v30;
                v32 = v44;
                bb = 4;
                continue;
            }
            6 => {
                v47 = v29 * v27;
                v48 = v47 + v31;
                v49 = (v25 as *mut u8).add((v48 as usize) * 4) as _;
                *(v49 as *mut f32) = v33;
                v9 = v21;
                v10 = v23;
                v11 = v25;
                v12 = v27;
                v13 = v29;
                v14 = v31;
                bb = 3;
                continue;
            }
            _ => break,
        }
    }
}

/// Safe launcher for `forge_kernel_matmul` with AVX2 runtime detection.
pub fn launch_forge_kernel_matmul(
    p0: *mut f32,
    p1: *mut f32,
    p2: *mut f32,
    p3: u32,
    grid_x: u32, grid_y: u32, grid_z: u32,
    block_x: u32, block_y: u32, block_z: u32,
) {
    if is_x86_feature_detected!("avx2") && is_x86_feature_detected!("fma") {
        // SAFETY: AVX2 + FMA detected at runtime.
        unsafe {
            launch_forge_kernel_matmul_avx2(
                p0,
                p1,
                p2,
                p3,
                grid_x, grid_y, grid_z, block_x, block_y, block_z,
            );
        }
    } else {
        // SAFETY: AVX2 not available; scalar path also uses #[target_feature].
        unsafe {
            launch_forge_kernel_matmul_scalar(
                p0,
                p1,
                p2,
                p3,
                grid_x, grid_y, grid_z, block_x, block_y, block_z,
            );
        }
    }
}

#[target_feature(enable = "avx2,fma")]
unsafe fn launch_forge_kernel_matmul_avx2(
    p0: *mut f32,
    p1: *mut f32,
    p2: *mut f32,
    p3: u32,
    grid_x: u32, grid_y: u32, grid_z: u32,
    block_x: u32, block_y: u32, block_z: u32,
) {
    for bz in 0..grid_z {
        for by in 0..grid_y {
            for bx in 0..grid_x {
                for tz in 0..block_z {
                    for ty in 0..block_y {
                        for tx in 0..block_x {
                            // SAFETY: kernel uses #[target_feature]; always unsafe.
                            unsafe {
                                forge_kernel_matmul(p0, p1, p2, p3, tx, ty, tz, bx, by, bz, block_x, block_y, block_z, grid_x, grid_y, grid_z);
                            }
                        }
                    }
                }
            }
        }
    }
}

#[target_feature(enable = "avx2,fma")]
unsafe fn launch_forge_kernel_matmul_scalar(
    p0: *mut f32,
    p1: *mut f32,
    p2: *mut f32,
    p3: u32,
    grid_x: u32, grid_y: u32, grid_z: u32,
    block_x: u32, block_y: u32, block_z: u32,
) {
    // Scalar fallback: same loop topology.
    for bz in 0..grid_z {
        for by in 0..grid_y {
            for bx in 0..grid_x {
                for tz in 0..block_z {
                    for ty in 0..block_y {
                        for tx in 0..block_x {
                            // SAFETY: kernel uses #[target_feature]; always unsafe.
                            unsafe {
                                forge_kernel_matmul(p0, p1, p2, p3, tx, ty, tz, bx, by, bz, block_x, block_y, block_z, grid_x, grid_y, grid_z);
                            }
                        }
                    }
                }
            }
        }
    }
}

